---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**


steps:
- name: env
  image: docker:git
  commands:
  - |
    if [ $CI_BUILD_EVENT = "tag" ]; then
      export BUILD_TAG=$DRONE_TAG
    else
      git fetch --tags
      export BUILD_TAG=$(git describe)
    fi
    export TAGPRE=$(shell echo "${BUILD_TAG}" | cut -c12-16)
    export TAGHPOOL=$(shell echo "${BUILD_TAG}" | cut -c16-23)
    export TAGHPOOL_PP=$(shell echo "${BUILD_TAG}" | cut -c16-23)
  - echo $$BUILD_TAG
  - echo $$TAGPRE
  - echo $$TAGHPOOL
  - echo $$TAGHPOOL_PP






# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock
