---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**


steps:
- name: env
  image: git
  commands:
  - |
    if [ $CI_BUILD_EVENT = "tag" ]; then
      export BUILD_TAG=$DRONE_TAG
    else

      export BUILD_TAG=$(git describe)
    fi
  - echo $$BUILD_TAG
  - export





# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock
