---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**


steps:
- name: env
  image: ubuntu
  commands:
  - echo $$DRONE_TAG
  - export





# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock
