---
kind: pipeline
type: docker
name: master

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/heads/master

steps:
- name: status
  image: kayuii/github-checker
  # failure: ignore
  commands:
  - URL=$(cat chia-og/version | github-checker hpool-dev/chia-miner)
  - XPROXY=$(echo "$URL" | grep xproxy)
  - HPOOL_LINUX=$(echo "$URL" | grep linux)
  - |
    if [ -n $XPROXY ]; then
      github-checker hpool-dev/chia-miner | tee chia-og/version
      echo $XPROXY | tee chia-og/xproxy_download_url
      echo $HPOOL_LINUX | tee chia-og/hpool_miner_download_url
      true
    else
      false
    fi

- name: havenewversion
  image: alpine/git
  environment:
    SSHKEY:
      from_secret: DRONE_HPOOL_MINER
  commands:
  - CUR_VERSION=$(cat chia-og/version | awk '{gsub(/\(|\)/,"");printf $2 "-" $3}')
  - mkdir -p "/root/.ssh"
  - ssh-keyscan github.com > /root/.ssh/known_hosts
  - echo "$SSHKEY" > /root/.ssh/id_key
  - chmod 400 /root/.ssh/id_key
  - git add --all
  - git commit -m "[drone CI] update chia-og version to $CUR_VERSION" --author="drone-build-bot <drone@vzxc.com>"
  - git tag "hpool-og-miner-$CUR_VERSION"
  - git status
  - git log --oneline --graph -n1
  - git tag -l -n2
  - ssh -T git@github.com
  when:
    status:
    - success
  depends_on:
  - status

- name: haven'tnewversion
  image: alpine/git
  commands:
  - cat chia-og/version | awk '{gsub(/\(|\)/,"");printf $2 "-" $3}'
  when:
    status:
    - failure
  depends_on:
  - status

# - name: push commit
#   image: appleboy/drone-git-push
#   settings:
#     branch: master
#     remote_name: git@github.com:Kayuii/hpool-miner.git
#     author_name: drone-build-bot
#     author_email: drone@vzxc.com
#     followtags: true
#     ssh_key:
#       from_secret: DRONE_HPOOL_MINER
#   depends_on:
#   - havenewversion


---
kind: pipeline
type: docker
name: check_chia_og

trigger:
  event:
  - cron

steps:
- name: check
  image: alpine/git
  commands:
  - github-checker hpool-dev/chia-miner
  - URL=$(cat chia-og/version | github-checker hpool-dev/chia-miner)
  - XPROXY=$(echo "$URL" | grep xproxy)
  - HPOOL_LINUX=$(echo "$URL" | grep linux)
  - |
    if [ -n $XPROXY ]; then
      mkdir -p chia-og/tmp
      wget -qO ./chia-og/tmp/xproxy.zip $XPROXY
      wget -qO ./chia-og/tmp/linux.zip $HPOOL_LINUX
      github-checker hpool-dev/chia-miner | tee chia-og/version
      cd chia-og
      unzip tmp/xproxy.zip -d "tmp"
      unzip tmp/linux.zip -d "tmp"
    else
      false
    fi
  # - export BUILD_TAG=$(cat version | awk '{gsub(/\(|\)/,"");printf $2 "-" $3}')

- name: update-tag
  image: alpine/git
  commands:
  - ls -lARFh
  when:
    status:
    - success

- name: publish-chia-og
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    platforms: "linux/amd64,linux/arm64,linux/arm"
    dockerfile: chia-og/Dockerfile
    repo: kayuii/hpool-miner
    context: chia-og
  when:
    event:
    - cron
    cron:
    - weekly

---
kind: pipeline
type: docker
name: build-tag

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/tags/**

# - name: publish-latest
#   image: thegeeklab/drone-docker-buildx
#   privileged: true
#   settings:
#     platforms: "linux/amd64,linux/arm64,linux/arm"
#     dockerfile: chia-og/Dockerfile
#     repo: kayuii/hpool-miner
#     context: chia-og
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password

steps:
- name: publish-chia-og
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    auto_tag: true
    platforms: "linux/amd64,linux/arm64,linux/arm"
    dockerfile: chia-og/Dockerfile
    repo: kayuii/hpool-miner
    context: chia-og
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/tags/hpool-og-miner-v**

# steps:
# - name: env
#   image: docker:git
#   commands:
#   - |
#     if [ $CI_BUILD_EVENT = "tag" ]; then
#       export BUILD_TAG=$DRONE_TAG
#     else
#       git fetch --tags
#       export BUILD_TAG=$(git describe)
#     fi
#     export TAGPRE=$(echo "${BUILD_TAG}" | cut -c12-16)
#     export TAGHPOOL=$(echo "${BUILD_TAG}" | cut -c16-23)
#     export TAGHPOOL_PP=$(echo "${BUILD_TAG}" | cut -c16-23)
#   - echo $$BUILD_TAG
#   - echo $$TAGPRE
#   - echo $$TAGHPOOL
#   - echo $$TAGHPOOL_PP


# - name: backend
#   image: plugins/docker
#   settings:
#     repo: kayuii/hpool-miner
#     dockerfile: ./Dockerfile
#     username: kayuii
#     password:
#       from_secret: DOCKER_PWD
#     tags: dev
#   depends_on:
#   - env
#   when:
#     ref:
#     - refs/heads/master

# depends_on:
#   - checkrepo

# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock

...
