language: ruby

branches:
  only:
  - master
  - /^hpool-miner-v.*$/
  - /^xproxy-v.*$/

services:
- docker

os: linux

dist: bionic

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - export DOCKER_BUILDKIT=1
  - docker run --rm --privileged tonistiigi/binfmt:latest --install all
  - docker buildx version
  - docker buildx create --platform linux/amd64,linux/arm64,linux/arm --use
  - docker buildx ls
  - docker buildx inspect --bootstrap

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[ "$TRAVIS_BRANCH" = "master" ]];then TRAVIS_TAG=$(git describe --abbrev=0); fi
  - TAG=$(echo "${TRAVIS_TAG:13}" | sed 's/\.//g' | sed 's/^[^-]*-//' )
  - echo "${TAG}"
  - if [[ "${TRAVIS_TAG:0:6}" = "xproxy" ]];then make xproxy; fi
  - if [[ "${TRAVIS_TAG:0:11}" = "hpool-miner" ]];then make TAG=${TAG} hpool-miner; fi
