#!/bin/bash

set -x
export DOCKER_CLI_EXPERIMENTAL=enabled

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

docker info

# docker run --privileged --rm tonistiigi/binfmt --version
docker run --rm --privileged tonistiigi/binfmt:latest --install all
# docker run --rm --privileged multiarch/qemu-user-static:register --reset -p yes

docker buildx version
# docker buildx create --use --name=mybuilder --driver docker-container
docker buildx create --platform linux/amd64,linux/arm64,linux/arm --use
docker buildx ls
set +x

docker buildx build --push -f Dockerfile -t $IMAGE_NAME --platform linux/amd64,linux/arm64,linux/arm .
